name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run test:lint

      - name: Compile
        run: npm run compile

  e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: install deps
        run: npm ci

      - name: start app
        run: npm start &

      - name: test
        run: npm run test:e2e
